### PR TITLE
Add xrandr

### PR DESCRIPTION
**Pull request by arthurbambou**
Fix `sh: xrandr: command not found`.

### CODE REVIEW

**Comment by arthurbambou** [comment]
bot, build

**Comment by arthurbambou** [comment]
bot, build

**Comment by x80486** [comment]
@arthurbambou, what's the intent/need for this dependency? Is it used by a plugin or are you trying to use it in the `Terminal` and getting that error message?

If `xrandr` is installed in your system, you should be able to use it.

**Comment by arthurbambou** [comment]
It needs to be on PATH for some library I use. But I was unable to make it work without this workaround...

**Comment by x80486** [comment]
@arthurbambou, you should be able to resolve this dependency as long as it is in your system, or installed through a package manager within your project.

If you are using the built-in `Terminal` within `IntelliJ IDEA`, I've found that you need to change to your shell, otherwise it won't pick up the environment settings — this only happens in the Flatpak version. For instance, I use `Bash`, and when I use the built-in `Terminal` I have to run `bash` before everything else from my system is recognized correctly.

**Pull request closed without merging**
